return {
  id = "lv1_motion",
  name = "Lv.1: 行内移動・瞬発力",
  description = "f, t, w, e, クォート操作",
  problems = {
    {
      id = "lv1_01",
      title = "引数の削除",
      mission = "余分な第2引数 `debug=True` を削除せよ",
      filetype = "python",
      cursor = { 1, 0 },
      initial = "def fetch(url, debug=True):\n    return http.get(url)",
      target = "def fetch(url):\n    return http.get(url)",
      ideal_keys = "f,da,",
      ideal_count = 5,
      explanation = "f, でカンマに跳び、da, でカンマごと引数を削除（または f,dw ）するのが最短です。",
    },
    {
      id = "lv1_02",
      title = "クォート内の書き換え",
      mission = "文字列の中身を 'prod' に書き換えよ",
      filetype = "python",
      cursor = { 1, 0 },
      initial = 'env = "staging"',
      target = 'env = "prod"',
      ideal_keys = 'ci"prod<Esc>',
      ideal_count = 8,
      explanation = 'カーソルがどこにあっても ci" を打てばクォート内を一撃で置換モードに入れます。',
    },
    {
      id = "lv1_03",
      title = "単語の即時置換",
      mission = "`user_id` を `account_id` に変更せよ",
      filetype = "python",
      cursor = { 1, 4 },
      initial = "var user_id = get_id();",
      target = "var account_id = get_id();",
      ideal_keys = "ciwaccount_id<Esc>",
      ideal_count = 14,
      explanation = "単語上ならどこでも ciw で単語を丸ごと書き換えられます。",
    },
    {
      id = "lv1_04",
      title = "括弧ごとの引数削除",
      mission = "`data.clean()` の呼び出し引数を消して空の `()` にせよ",
      filetype = "csharp",
      cursor = { 1, 0 },
      initial = "Process(data.clean(raw_text, strict: true));",
      target = "Process(data.clean());",
      ideal_keys = "2f(di(",
      ideal_count = 6,
      explanation = "di( を使えば、括弧の内側の引数群をカンマごと一網打尽に消去できます。",
    },
    {
      id = "lv1_05",
      title = "行内ジャンプと1文字置換",
      mission = "等号の不等号ミス `x == 10` を `x >= 10` に修正せよ",
      filetype = "python",
      cursor = { 1, 0 },
      initial = "if x == 10:\n    print('ok')",
      target = "if x >= 10:\n    print('ok')",
      ideal_keys = "f=r>",
      ideal_count = 4,
      explanation = "f= で等号に跳び、r> で文字を直接上書きするのが最速です。",
    },
  },
}
