return {
  id = "lv2_textobj",
  name = "Lv.2: 構造・テキストオブジェクト",
  description = "テキストオブジェクト, ドット反復(.)",
  problems = {
    {
      id = "lv2_01",
      title = "波括弧ブロックの全削除",
      mission = "関数の中身を空にして `pass` だけにせよ",
      filetype = "csharp",
      cursor = { 2, 4 },
      initial = "void Setup() {\n    InitConfig();\n    ValidateEnv();\n    Connect();\n}",
      target = "void Setup() {\n    pass\n}",
      ideal_keys = "ci{pass<Esc>",
      ideal_count = 8,
      explanation = "波括弧の中ならどこでも ci{ で中身を丸ごと置き換えられます。",
    },
    {
      id = "lv2_02",
      title = "ドットコマンド反復",
      mission = "すべての `old_val` を `new_val` に変更せよ",
      filetype = "python",
      cursor = { 1, 4 },
      initial = "a = old_val\nb = old_val\nc = old_val",
      target = "a = new_val\nb = new_val\nc = new_val",
      ideal_keys = "ciwnew_val<Esc>j.j.",
      ideal_count = 14,
      explanation = "1行目を ciw で変更したら、次行で j. を叩くだけで同じ変更を繰り返せます。",
    },
    {
      id = "lv2_03",
      title = "HTML/XMLタグの中身書き換え",
      mission = "タグの中身を 'Home' に変更せよ",
      filetype = "xml",
      cursor = { 1, 4 },
      initial = "<button class=\"nav\">Dashboard</button>",
      target = "<button class=\"nav\">Home</button>",
      ideal_keys = "citHome<Esc>",
      ideal_count = 8,
      explanation = "cit でタグに囲まれた内側を一撃で書き換えられます。",
    },
  },
}
